# Generated by Django 4.2.6 on 2023-11-02 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('profile_image', models.ImageField(blank=True, default='member/avatar-profile.jpg', null=True, upload_to='member/')),
            ],
        ),
        migrations.CreateModel(
            name='Mitra',
            fields=[
                ('mitra_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('profile_image', models.ImageField(blank=True, default='mitra/avatar-profile.jpg', null=True, upload_to='mitra/')),
            ],
        ),
    ]
