# Generated by Django 4.2.6 on 2023-11-05 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('profile_image', models.ImageField(blank=True, default='member/avatar-profile.jpg', null=True, upload_to='member/')),
                ('is_verified', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user_type', models.CharField(default='member', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mitra',
            fields=[
                ('mitra_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('start_time', models.TimeField(default='00:00:00')),
                ('end_time', models.TimeField(default='00:00:00')),
                ('twitter_site', models.URLField(null=True)),
                ('fb_site', models.URLField(null=True)),
                ('ig_site', models.URLField(null=True)),
                ('linkedin_site', models.URLField(null=True)),
                ('yt_site', models.URLField(null=True)),
                ('profile_image', models.ImageField(blank=True, default='mitra/avatar-profile.jpg', null=True, upload_to='mitra/')),
                ('is_verified', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user_type', models.CharField(default='mitra', max_length=10)),
            ],
        ),
    ]
