# Generated by Django 4.2.6 on 2023-11-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expired_time',
            field=models.IntegerField(default=7),
        ),
    ]
