# Generated by Django 4.2.6 on 2023-11-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitra',
            name='fb_site',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='mitra',
            name='ig_site',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='mitra',
            name='linkedin_site',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='mitra',
            name='twitter_site',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='mitra',
            name='yt_site',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
