# Generated by Django 4.2.6 on 2024-07-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='blog/default-blog.jpg', null=True, upload_to='blog/')),
                ('tag', models.CharField(default='', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
