# Generated by Django 4.2.6 on 2023-11-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='mitra',
            name='user_type',
        ),
    ]
