# Generated by Django 4.2.6 on 2023-11-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mitra_city_mitra_end_time_mitra_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitra',
            name='fb_site',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mitra',
            name='ig_site',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mitra',
            name='linkedin_site',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mitra',
            name='twitter_site',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mitra',
            name='yt_site',
            field=models.URLField(null=True),
        ),
    ]
