# Generated by Django 4.2.6 on 2023-11-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mitra_fb_site_alter_mitra_ig_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylist',
            name='price',
            field=models.FloatField(),
        ),
    ]
