# Generated by Django 4.2.6 on 2023-11-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='expired_time',
        ),
    ]
