# Generated by Django 4.2.6 on 2023-11-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mitra_fb_site_mitra_ig_site_mitra_linkedin_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitra',
            name='mitra_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
