# Generated by Django 4.2.6 on 2023-11-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_activitylist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonial_id', models.AutoField(primary_key=True, serialize=False)),
                ('testimonial', models.TextField(default='')),
                ('rating', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_testimonial', to='app.activitylist')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_testimonial', to='app.member', to_field='uuid')),
                ('mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitra_testimonial', to='app.mitra', to_field='uuid')),
            ],
            options={
                'verbose_name': 'Testimoni',
                'verbose_name_plural': 'Daftar Testimoni',
            },
        ),
    ]
