# Generated by Django 4.2.6 on 2023-11-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mitra_fb_site_alter_mitra_ig_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActitityList',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('day', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('duration', models.TimeField()),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('learning_method', models.TextField(default='')),
                ('benefit', models.TextField()),
                ('detail_time', models.TextField(default='')),
                ('requirements', models.TextField(default='')),
                ('additional_information', models.TextField(default='')),
                ('activity_image', models.ImageField(blank=True, default='activity/default-activity.jpg', null=True, upload_to='activity/')),
                ('activity_status', models.CharField(choices=[('pending', 'Pending'), ('terbit', 'Terbit'), ('ditolak', 'Ditolak')], default='pending', max_length=10)),
                ('mitra_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mitra')),
            ],
            options={
                'verbose_name': 'Kegiatan',
                'verbose_name_plural': 'Daftar Kegiatan',
            },
        ),
    ]
