# Generated by Django 4.2.6 on 2023-11-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_transaction_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('wfp', 'Menunggu Pembayaran'), ('success', 'Sukses'), ('paid', 'Lunas'), ('failed', 'Gagal'), ('refund', 'Refund'), ('expired', 'Kadaluwarsa'), ('cancel', 'Dibatalkan')], default='Menunggu Pembayaran', max_length=50),
        ),
    ]
