# Generated by Django 4.2.6 on 2023-11-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_actititylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='actititylist',
            name='reason_rejected',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
