# Generated by Django 4.2.6 on 2023-11-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Sukses', 'Sukses'), ('Lunas', 'Lunas'), ('Gagal', 'Gagal'), ('Refund', 'Refund'), ('Kadaluwarsa', 'Kadaluwarsa'), ('Dibatalkan', 'Dibatalkan')], default='Menunggu Pembayaran', max_length=50),
        ),
    ]
