# Generated by Django 4.2.6 on 2023-11-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_actititylist_reason_rejected'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActitityList',
            new_name='ActivityList',
        ),
    ]
