# Generated by Django 4.2.6 on 2023-11-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_transaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Transfer Bank', 'Transfer Bank'), ('OVO', 'OVO'), ('GoPay', 'GoPay'), ('LinkAja', 'LinkAja'), ('Dana', 'Dana'), ('ShopeePay', 'ShopeePay'), ('Alfamart', 'Alfamart'), ('Indomaret', 'Indomaret')], default='Transfer Bank', max_length=50),
        ),
    ]
