# Generated by Django 4.2.6 on 2023-11-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_actititylist_activitylist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylist',
            old_name='reason_rejected',
            new_name='message_status',
        ),
    ]
