# Generated by Django 4.2.6 on 2023-11-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_reason_rejected_activitylist_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylist',
            name='detail_time',
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='duration',
            field=models.IntegerField(default=''),
        ),
    ]
