# Generated by Django 4.2.6 on 2023-11-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_free',
            field=models.BooleanField(choices=[(True, True), (False, False)], default=False),
        ),
    ]
