# Generated by Django 4.2.6 on 2023-11-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_activitylist_detail_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylist',
            name='mitra_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitra_activity', to='app.mitra', to_field='uuid'),
        ),
    ]
