# Generated by Django 4.2.6 on 2023-11-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_transaction_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
