# Generated by Django 4.2.6 on 2024-07-07 22:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_activitylist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylist',
            name='additional_information',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='benefit',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='description',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='learning_method',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='requirements',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
