# Generated by Django 4.2.6 on 2023-11-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_activitylist_mitra_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylist',
            name='age',
            field=models.TextField(default=''),
        ),
    ]
