# Generated by Django 4.2.6 on 2023-11-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_transaction_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='mitra',
        ),
    ]
