# Generated by Django 4.2.6 on 2023-11-15 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_testimonial_mitra'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulTransaction',
            fields=[
                ('success_id', models.AutoField(primary_key=True, serialize=False)),
                ('success_date', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='successful_transaction', to='app.transaction')),
            ],
        ),
    ]
