# Generated by Django 4.2.6 on 2023-11-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_successfultransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuccessfulTransaction',
        ),
    ]
