# Generated by Django 4.2.6 on 2024-07-09 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_testimonial_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.activitylist')),
            ],
        ),
    ]
