# Generated by Django 4.2.6 on 2024-02-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
