# Generated by Django 4.2.6 on 2023-10-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pages', '0002_rename_customer_member_mitra_is_verified_mitra_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/member/default.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mitra',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='media'),
        ),
    ]
