# Generated by Django 4.2.6 on 2023-10-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pages', '0003_member_profile_image_mitra_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/member/avatar-profile.jpg', null=True, upload_to=''),
        ),
    ]
