# Generated by Django 4.2.6 on 2023-11-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pages', '0007_member_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
