# Generated by Django 4.2.6 on 2023-10-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.IntegerField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='mitra',
            name='number',
            field=models.IntegerField(max_length=13, unique=True),
        ),
    ]
