# Generated by Django 4.2.6 on 2023-10-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0003_alter_customer_number_alter_mitra_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
