# Generated by Django 4.2.6 on 2023-10-19 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0005_customer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
